### ISSUE TITLE
handling the domains excluded from the Wayback Machine

### ISSUE THREAD

**Issue by 07416** [overcast07/wayback-machine-spn-scripts#13]
[the website](https://web.archive.org/web/*/https://www.nohomers.net/) reports:

>Sorry.

>This URL has been excluded from the Wayback Machine.

it appears that currently the script reports excluded websites as successful submissions, for instance:

    spn.sh https://www.nohomers.net/ 

outputs (timestamps and the data folder stripped):

```
Created data folder ~/spn-data/
 [Job submitted] https://www.nohomers.net/
 [Job completed] https://www.nohomers.net/
```

the internal archive.org 'block list' reports errors (contains at least the said `archive.org` domain):

>This URL is in the Save Page Now service block list and cannot be captured. Please email us at "`info@archive.org`" if you would like to discuss this more.

**Comment by overcast07** [comment]
Information about the block list isn't provided by the Save Page Now service. In SPN there are some sites where archiving works fine and no error messages are shown, but the domain itself is actually blocked and you can't view the captures. For example, if you archive a Dropbox download link ending in `?dl=1`, SPN won't report any problems, and the capture of the URL that the submitted URL redirects to will be viewable, _but_ certain parts of the main dropbox.com domain are blocked so the capture of the actual submitted URL won't be viewable. We could infer from this that the captures are actually kept in spite of not being visible, but I don't know for sure.

There is no archive.ph API, and the site maintainer (it's literally just one person running it) probably doesn't plan to add one. Bot stuff is actively discouraged on that site and you can get a CAPTCHA if you submit more than a few links.

Maybe you could poll the CDX API before every capture but it's not necessarily something everyone would want to enable. If the captures are actually being stored, maybe some people would consider that to be a successful archival of the content despite the captures not being visible.
