### ISSUE TITLE
Consider adding this to AUR?

### ISSUE THREAD

**Issue by otuva** [overcast07/wayback-machine-spn-scripts#14]
~~Hi, this script is very good would you consider adding it to the arch user repo?~~

This issue was a draft and I did it myself. So instead of opening a PR I'm just opening an issue 

[Link to the package](https://aur.archlinux.org/packages/wayback-spn-script-git)

**Comment by overcast07** [comment]
Is there anything I need to do? I'm not sure if this means I need to update the code/documentation of the script or something lol

**Comment by otuva** [comment]
Well, I opened this issue to just let you and the people who might use this script in the future know. 

But if you'd like to maintain it yourself on AUR, I can hand it to you. 

Or if you'd like, you can add arch-based distro installation under `installation` header like:

`yay -S wayback-spn-script-git`
