### ISSUE TITLE
List of URLs, add time delay argument between requests.

### ISSUE THREAD

**Issue by Delvin4519** [overcast07/wayback-machine-spn-scripts#21]
Is it possible to add an argument to time delay requests when using a list of URLs to archive? i.e. after a successful request, wait 3-12 seconds before starting the next archive upload?

I have a problem where even when I use an argument to limit to a single thread for tasks, the script is still sending the archive requests too fast, and after 4 successful uploads, the remaining requests errors out and times out.

**Comment by swiftgeek** [comment]
Ran into similar issue, added extra `sleep 60` just at start of `capture()` function
https://github.com/overcast07/wayback-machine-spn-scripts/blob/4cc1641e4d31bab7ca90e92b53d4b595bbc9b21b/spn.sh#L258-L259

Then used script with `./spn.sh -n -p 1 urls.txt`

**Comment by 07416** [comment]
Should running the script with the `p 1 -w 60` entirely prevent from being rate-limited? I waited for around 12 hours, started my capture task again.

[Request failed] https://example.com/
You have already reached the limit of active Save Page Now sessions. Please wait for a minute and then try again.
