### ISSUE TITLE
Links to HTML files always end up in failed despite being successfully captured

### ISSUE THREAD

**Issue by heartlessglasses** [overcast07/wayback-machine-spn-scripts#25]
Title. Links to HTML files are never marked down as successes or show up in captures.log, but a manual check on the Wayback Machine shows that they were in fact captured. This also results in a loop where the program keeps trying the same URLs linking to HTML files and keeps failing and has to be manually stopped.

Example URL (chosen randomly from the same site where I noticed this issue): https://archiveofourown.org/downloads/22187314/Rebirth.html?updated_at=1679933233, which redirects to https://download.archiveofourown.org/downloads/22187314/Rebirth.html?updated_at=1679933233 with a 301. I had both in the input file. Both are marked as failed despite being captured.

**Comment by overcast07** [comment]
I think this is a bug in SPN. When I tried to archive the second URL you linked, SPN returned the error message "Save Page Now browser crashed on URL https://download.archiveofourown.org/downloads/22187314/Rebirth.html?updated_at=1679933233." If the script isn't able to get the data from SPN about what was archived, then the URL can't be marked as having been captured successfully.

**Comment by heartlessglasses** [comment]
Thanks for investigating, I will contact them. Do you know if the script has some mechanism for stopping that looping that might be failing?
