### ISSUE TITLE
Initial URLs aren't de-duplicated

### ISSUE THREAD

**Issue by mskiptr** [overcast07/wayback-machine-spn-scripts#36]
When using `spn` for the first time I forgot to run the URLs list through `sort | uniq`. This has caused a lot of duplicate job submissions immediately followed by lines like:

> `The same snapshot had been made 59 seconds ago. You can make new capture of this URL after 1 hour.`

Is there any reason not to remove duplicate lines from the input? It's pretty pointless to request the exact same page to be saved twice. As far as I can see, some de-duplication logic already happens for all the outlinks, so why not apply this logic to seed URLs as well?

**Comment by exurd** [comment]
Just checked the script; it does dedupe `index.txt`, which gets used when resuming a data folder.
https://github.com/overcast07/wayback-machine-spn-scripts/blob/31d6bf1cf8fa7ea6150eb7face5c4780368263fe/spn.sh#L255
If index.txt is being deduped, then the `$list` variable should be deduped as well...

**Comment by overcast07** [comment]
Fixed by #37
